[package]
name = "withdraw"
type = "bin"
authors = [""]
compiler_version = "1.0.0"

[dependencies]
poseidon_tree = { path = "../poseidon_tree" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }